spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://192.168.110.120:3306/minshengoa?characterEncoding=utf-8
      url: jdbc:mysql://localhost:3306/minshengoa?characterEncoding=utf-8
      username: root
      password: root
      # Druid连接池配置
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化
      initialSize: 3
      # 最大
      maxActive: 20
      # 最小
      minIdle: 1
      # 最大连接等待超时时间
      maxWait: 8000
      # 打开PSCache,并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间,单位是毫秒
      minEvictableIdleTimeMillis: 300000
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
server:
    port: 80
##队列
messages:
  queue: mail_queue









