spring:
   profiles:
     active:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://139.155.1.9:3306/myoa?characterEncoding=utf-8
      username: root
      password: root
      # Druid连接池配置
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化
      initialSize: 3
      # 最大
      maxActive: 20
      # 最小
      minIdle: 1
      # 最大连接等待超时时间
      maxWait: 8000
      # 打开PSCache,并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间,单位是毫秒
      minEvictableIdleTimeMillis: 300000
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      open-in-view: true
   http:
      encoding:
         charset: UTF-8
         force: true

   servlet:
      multipart:
         max-file-size: 1000200000
         max-request-size:  150000000
server:
    port: 8081


fdfs:
  so-timeout: 1501
  connect-timeout: 2000
  resHost: 139.155.1.9
  storagePort: 80
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 139.155.1.9:22122

---
spring:
   profiles: local
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/myoa?characterEncoding=utf-8
      username: root
      password: root
      # Druid连接池配置
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化
      initialSize: 3
      # 最大
      maxActive: 20
      # 最小
      minIdle: 1
      # 最大连接等待超时时间
      maxWait: 8000
      # 打开PSCache,并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间,单位是毫秒
      minEvictableIdleTimeMillis: 300000
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      open-in-view: true
   http:
      encoding:
         charset: UTF-8
         force: true

   servlet:
      multipart:
         max-file-size: 1000200000
         max-request-size:  150000000
server:
    port: 8081


fdfs:
  so-timeout: 1501
  connect-timeout: 2000
  resHost: 47.112.143.90
  storagePort: 80
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 47.112.143.90:22122














